import { GameTemplate } from "../stores/gameBuilderStore";

export const gameTemplates: Record<string, GameTemplate[]> = {
	grid: [
		{
			id: "sudoku-9x9",
			name: "Sudoku 9x9",
			type: "sudoku",
			category: "grid",
			icon: "grid-outline",
			description: "Classic 9x9 Sudoku puzzle",
			defaultConfig: { size: 9 },
		},
		{
			id: "sudoku-6x6",
			name: "Sudoku 6x6",
			type: "sudoku",
			category: "grid",
			icon: "grid-outline",
			description: "Smaller 6x6 Sudoku variant",
			defaultConfig: { size: 6 },
		},
		{
			id: "kenken",
			name: "KenKen",
			type: "kenken",
			category: "grid",
			icon: "calculator-outline",
			description: "Math puzzle with cage constraints",
			defaultConfig: { size: 6 },
		},
		{
			id: "nonogram",
			name: "Nonogram",
			type: "nonogram",
			category: "grid",
			icon: "image-outline",
			description: "Picture logic puzzle",
			defaultConfig: { rows: 10, cols: 10 },
		},
		{
			id: "slitherlink",
			name: "Slitherlink",
			type: "slitherlink",
			category: "grid",
			icon: "link-outline",
			description: "Loop puzzle with number clues",
			defaultConfig: { rows: 10, cols: 10 },
		},
		{
			id: "futoshiki",
			name: "Futoshiki",
			type: "futoshiki",
			category: "grid",
			icon: "code-working-outline",
			description: "Inequality puzzle",
			defaultConfig: { size: 5 },
		},
		{
			id: "magic-square",
			name: "Magic Square",
			type: "magicSquare",
			category: "grid",
			icon: "square-outline",
			description: "Numbers sum to same value",
			defaultConfig: { size: 3 },
		},
	],
	path: [
		{
			id: "hidato",
			name: "Hidato",
			type: "hidato",
			category: "path",
			icon: "navigate-outline",
			description: "Number path puzzle",
			defaultConfig: { rows: 5, cols: 5 },
		},
		{
			id: "zip",
			name: "Zip",
			type: "zip",
			category: "path",
			icon: "git-branch-outline",
			description: "Connect numbered cells",
			defaultConfig: { rows: 5, cols: 5 },
		},
	],
	word: [
		{
			id: "wordle",
			name: "Wordle",
			type: "wordle",
			category: "word",
			icon: "text-outline",
			description: "Word guessing game",
			defaultConfig: { wordLength: 5 },
		},
		{
			id: "word-chain",
			name: "Word Chain",
			type: "wordChain",
			category: "word",
			icon: "link-outline",
			description: "Connect words by changing one letter",
			defaultConfig: {},
		},
		{
			id: "crossword",
			name: "Crossword",
			type: "crossword",
			category: "word",
			icon: "grid-outline",
			description: "Classic crossword puzzle",
			defaultConfig: { rows: 15, cols: 15 },
		},
	],
	logic: [
		{
			id: "sequencing",
			name: "Sequencing",
			type: "sequencing",
			category: "logic",
			icon: "list-outline",
			description: "Order items based on rules",
			defaultConfig: { theme: "people", numSlots: 5 },
		},
		{
			id: "mastermind",
			name: "Mastermind",
			type: "mastermind",
			category: "logic",
			icon: "color-palette-outline",
			description: "Code breaking game",
			defaultConfig: { codeLength: 4 },
		},
		{
			id: "logic-grid",
			name: "Logic Grid",
			type: "logicGrid",
			category: "logic",
			icon: "grid-outline",
			description: "Deductive reasoning puzzle",
			defaultConfig: {},
		},
	],
	math: [
		{
			id: "quick-math",
			name: "Quick Math",
			type: "quickMath",
			category: "math",
			icon: "calculator-outline",
			description: "Fast arithmetic challenges",
			defaultConfig: { numProblems: 10 },
		},
	],
	custom: [
		{
			id: "riddle",
			name: "Riddle",
			type: "riddle",
			category: "custom",
			icon: "help-circle-outline",
			description: "Brain teaser with multiple choice",
			defaultConfig: {},
		},
		{
			id: "alias",
			name: "Alias",
			type: "alias",
			category: "custom",
			icon: "book-outline",
			description: "Word association game",
			defaultConfig: {},
		},
		{
			id: "trivia",
			name: "Trivia",
			type: "trivia",
			category: "custom",
			icon: "trophy-outline",
			description: "Knowledge quiz",
			defaultConfig: { numQuestions: 5 },
		},
	],
};

